//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace USF.GestionExpertTribunal.Entities.Models
{
	public class Demande
	{
		private int id;

		private string libelle;

		private string commantaire;

		private DateTime dateCreation;

		private DateTime dateModification;

		private string code;

		private bool isActive;

		private double prix;

		private string dateFin;

		private TypeDemande typeDemande;

		private Expert expert;

		public virtual int Id
		{
			get { return this.id; }
			set { this.id = value; }
		}

		public virtual string Libelle
		{
			get { return this.libelle; }
			set { this.libelle = value; }
		}

		public virtual string Commantaire
		{
			get { return this.commantaire; }
			set { this.commantaire = value; }
		}

		public virtual DateTime DateCreation
		{
			get { return this.dateCreation; }
			set { this.dateCreation = value; }
		}

		public virtual DateTime DateModification
		{
			get { return this.dateModification; }
			set { this.dateModification = value; }
		}

		public virtual string Code
		{
			get { return this.code; }
			set { this.code = value; }
		}

		public virtual bool IsActive
		{
			get { return this.isActive; }
			set { this.isActive = value; }
		}

		public virtual double Prix
		{
			get { return this.prix; }
			set { this.prix = value; }
		}

		public virtual string DateFin
		{
			get { return this.dateFin; }
			set { this.dateFin = value; }
		}

		public virtual TypeDemande TypeDemande
		{
			get { return this.typeDemande; }
			set { this.typeDemande = value; }
		}

		public virtual Expert Expert
		{
			get { return this.expert; }
			set { this.expert = value; }
		}

	}
}
