//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace USF.GestionExpertTribunal.Entities.Models
{
	public class Experts
	{
		private int id;

		private string nom;

		public virtual int Id
		{
			get { return this.id; }
			set { this.id = value; }
		}

		public virtual string Nom
		{
			get { return this.nom; }
			set { this.nom = value; }
		}

	}
}
