//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace USF.GestionExpertTribunal.Entities.Models
{
	public class ExpertDossierLines
	{
		private int id;

		private string nom;

		private DateTime dateAffectation;

		private Dossier dossier;

		private Expert expert;

		public virtual int Id
		{
			get { return this.id; }
			set { this.id = value; }
		}

		public virtual string Nom
		{
			get { return this.nom; }
			set { this.nom = value; }
		}

		public virtual DateTime DateAffectation
		{
			get { return this.dateAffectation; }
			set { this.dateAffectation = value; }
		}

		public virtual Dossier Dossier
		{
			get { return this.dossier; }
			set { this.dossier = value; }
		}

		public virtual Expert Expert
		{
			get { return this.expert; }
			set { this.expert = value; }
		}

	}
}
