//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace USF.GestionExpertTribunal.Entities.Models
{
	public class Portail
	{
		private int id;

		private DateTime delaiModifier;

		private double prixModifier;

		private Expert expert;

		private Dossier dossier;

		private Greffier greffier;

		public virtual int Id
		{
			get { return this.id; }
			set { this.id = value; }
		}

		public virtual DateTime DelaiModifier
		{
			get { return this.delaiModifier; }
			set { this.delaiModifier = value; }
		}

		public virtual double PrixModifier
		{
			get { return this.prixModifier; }
			set { this.prixModifier = value; }
		}

		public virtual Expert Expert
		{
			get { return this.expert; }
			set { this.expert = value; }
		}

		public virtual Dossier Dossier
		{
			get { return this.dossier; }
			set { this.dossier = value; }
		}

		public virtual Greffier Greffier
		{
			get { return this.greffier; }
			set { this.greffier = value; }
		}

	}
}
